### ISSUE TITLE
Fix adding/removing while looping

### ISSUE THREAD

**Issue by ayebear** [Lastresort92/OCS#2]
There should be a better solution to this line in the PackedArray class:
PackedArray() {elements.reserve(100000);}

Maybe add some sort of queuing system so elements are only added/removed after looping.

**Comment by kevinwmiller** [comment]
http://www.newegg.com/Product/Product.aspx?Item=N82E16820233738

**Comment by kevinwmiller** [comment]
Really though... I will fix my hack.

**Comment by kevinwmiller** [comment]
These commands can now be stored in a command and then executed after the loop is finished. Support for the option to automatically execute is coming
