### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by ayebear** [Lastresort92/OCS#5]
When running the test program, I'm getting this:
OCS_Test: Commands_Test.cc:116: void cmdtest::TEST_DESTROY_OBJECT_COMMAND(): Assertion `objManager.getTotalObjects() == 2' failed.

I checked the total number of objects, and it goes down to 1 after calling execute() on the same command twice. So it shouldn't be deleting an object with an invalid ID.

It could be an issue with PackedArray, or something else.

**Comment by kevinwmiller** [comment]
=(

**Comment by ayebear** [comment]
PackedArray isn't setting deleted elements' indices to -1 (invalid index). The line that was doing that was commented out for some reason. This is probably the cause of the issue.

**Comment by kevinwmiller** [comment]
Should be fixed now and will be in next update
