### ISSUE TITLE
Component name binding

### ISSUE THREAD

**Issue by ayebear** [Lastresort92/OCS#8]
Make binding names to component types cleaner and easier to do. One possible way is to have a static getName function for components. This way, you could optionally define getName, and inside of the registerComponent function, it would bind the name if needed.

Edit: This would probably only work if you initially added all of the components though.

**Comment by kevinwmiller** [comment]
Could you give me an example? It's been a while since I looked at it, but doesn't binding a component just require something like 

"objManager.bindComponentToString<Position>("Position");"?

If not, it should be and I'll make it that way

**Comment by kevinwmiller** [comment]
It took away my angle brackets

I could add this syntax I suppose,

objManager.bindComponentToString&lt;Position&gt;&lt;Name&gt;&lt;Something&gt;("Position", "Name", "Something");

**Comment by kevinwmiller** [comment]
And I still messed it up, you know how templates look

**Comment by ayebear** [comment]
It currently works like this:
objects.bindStringToComponent<Component>("Component");
But it is not variadic, so you need a bunch of these lines. I was just thinking it would be easier to define this as part of the component, although C++ might not work well in that way.

**Comment by kevinwmiller** [comment]
Should be easy to do to do that. I was just lazy

**Comment by ayebear** [comment]
A possible solution is to allow defining the name inside the component as a static string:

```
struct Position: public ocs::Component<Position>
{
    ...
    static const std::string name = "Position";
};
```

Then the code that registers components could use static polymorphism to get the name and bind it to its type.

**Comment by ayebear** [comment]
I resorted to a macro initially but it's still terrible: https://github.com/ayebear/Multiversal/blob/master/src/game/componentstrings.cpp

**Comment by kevinwmiller** [comment]
One issue, as you pointed out, is you have to use the component in some way so it registers with the object manager before you can have string support with it.

I added some code to allow a component's name to be bound once it registers by overloading the 'name' function in the component.

e.g.

struct Position ....
    std::string name() 
    {
        static const std::string compName = "Position";
        return compName;
    }

Overloading a function instead of setting a variable to avoid a redefinition of the default value set in the BaseComponent class.

I'll need to think of some workaround to the use order issue though

**Comment by kevinwmiller** [comment]
Closing for now. May reopen
