### ISSUE TITLE
Implement an assignComponent() method

### ISSUE THREAD

**Issue by ayebear** [Lastresort92/OCS#9]
This would be part of the ObjectManager. It would check if the component exists, add a new one if it doesn't, or set it if it does.

This would cover most use cases, since add/set won't always work depending on if the component already exists. Most of the time you'd want to just replace it.

Update: Unless you can show me use cases for "add" and "set" when there is an "assign", then you could probably remove them from the public interface.

**Comment by kevinwmiller** [comment]
Done. Just adding tests
